---
- hosts: "{{ hostname }}"

  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter_username }}"
    GOVC_PASSWORD: "{{ vcenter_password }}"
    GOVC_URL: "https://{{ vcenter_hostname }}"
    GOVC_INSECURE: 1

  tasks:
  - name: get user home directory
    shell: >
            getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: Setting facts 
    set_fact:
      templateName : "{{ templateName }}"
      folder : "/{{ vmware_datacenter }}/vm/{{ config.clusterName }}"
      datastore: "{{ vmware_datastore }}"

  - name: Power On bootstrap nodes
    command: "/usr/local/bin/govc vm.power -on  bootstrap"

  - pause:
    seconds: 45

  - name: Power On Master Nodes
    include: boot-coreos-vms-loop.yml
    loop: "{{ masters }}"

  - name: "Wait for {{ api_endpoint }}"
    uri:
      url: "{{ api_endpoint }}:22623/config/master"
    register: result
    until: "'failed' not in result and result.content.find('OK') != -1"
    retries: 18
    delay: 10

  - name: Power On Worker Nodes
    include: boot-coreos-vms-loop.yml
    loop: "{{ workers }}"