---
- hosts: "{{ hostname }}"

  environment:
    KUBECONFIG: /root/install-dir/auth/kubeconfig

  tasks:
  - name: Waiting for bootstrap Complete
    shell: |
      openshift-install --dir=/root/install-dir wait-for bootstrap-complete --log-level debug 2>&1 | tee /tmp/bootstrap-complete.log &
    async: 3600
    poll: 5
    changed_when: false
  - name: Wait for bootstrap complete to be found in file
    wait_for:
      path: "/tmp/bootstrap-complete.log"
      search_regex: "Bootstrap status: complete"
      delay: 30
      timeout: 900
      msg: "DEBUG Bootstrap status: complete "
  - name: Remove /tmp/bootstrap-complete.log
    file:
      path: /tmp/bootstrap-complete.log
      state: absent

  - name: Verifying oc commands
    command: oc whoami

  - name: Get Ready nodes
    command: oc get nodes

  - name:  Review  and approve the pending certificate signing requests
    command: "curl -k --silent {{ api_endpoint }}:22623/config/master"
    register: result
    until: result.stdout.find("Pending") != -1
    retries: 100
    delay: 30
    changed_when: false
