---
- hosts: "{{ hostname }}"

  environment:
    KUBECONFIG: /root/install-dir/auth/kubeconfig

  tasks:
  - name: Waiting for bootstrap Complete
    shell: |
      openshift-install --dir=/root/install-dir wait-for bootstrap-complete --log-level debug 2>&1 | tee /tmp/bootstrap-complete.log &
    register: install_status
    until: "'Bootstrap status: complete' in install_status.stdout"
    retries: 120
    delay: 30

  - name: "Install Status"
    debug:
      msg: "{{ install_status }}"

  - name: Remove /tmp/bootstrap-complete.log
    file:
      path: /tmp/bootstrap-complete.log
      state: absent

  - name: Verifying oc commands
    command: oc whoami
    environment:
      KUBECONFIG: "/root/install-dir/auth/kubeconfig"

  - name: Get Ready nodes
    command: oc get nodes
    environment:
      KUBECONFIG: "/root/install-dir/auth/kubeconfig"

  - name:  Review  and approve the pending certificate signing requests
    script: approve-ocp-certs.sh
    environment:
      KUBECONFIG: "/root/install-dir/auth/kubeconfig"

  - name: Waiting for installation to complete
    shell: |
      openshift-install --dir=/root/install-dir wait-for install-complete --log-level debug 2>&1 | tee /tmp/install-complete.log &
    register: install_status
    until: "'Install complete!' in install_status.stdout"
    retries: 120
    delay: 30

  - name: "Install Complete"
    debug:
      msg: "Install is compelte {{ install_status.stdout }}"
