- hosts: "{{ hostname }}"
  
  tasks:

  - name: get user home directory
    shell: >
            getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: clean up iginition directory 
    script: | 
      cd /var/www/html/ignition/ && rm -rf *
    when: clean is defined
    
  - name: configure web server files
    script: "{{ user_home.stdout }}/configure-webserver.sh --some-argument  {{ user_home.stdout }}"