- hosts: "{{ hostname }}"

  tasks:

  - name: get user home directory
    shell: >
            getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: Ansible delete /var/www/html/ignition/ files
    find:
      paths: /var/www/html/ignition/
      patterns: "*.*"
    register: files_to_delete
    when: clean is defined

  - name: Ansible remove files in  /var/www/html/ignition/
    file:
      path:  "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    when: clean is defined

  - name: configure web server files
    script: "configure-webserver.sh --some-argument  {{ user_home.stdout }}"
    ignore_errors: no
