- hosts: "{{ hostname }}"
  
  tasks:
  - name: get user home directory
    shell: >
            getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: Copy the all the ignition files over to the webserver
    command: "/usr/bin/cp -avi {{ user_home.stdout }}/install-dir/*.ign /var/www/html/ignition/"
  
  - name: Copy the all the static ip  files over to the webserver
    command: "/usr/bin/cp {{ user_home.stdout }}/ocp4-utils/configFiles/*.com /var/www/html/ignition/"  
