- hosts: "{{ hostname }}"
  
  tasks:

  - name: get user home directory
    shell: >
            getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: Ansible delete /var/www/html/ignition/ files
    find:
      paths: /etc/Ansible
      patterns: "*.*"
    register: files_to_delete
    when: clean is defined
    delegate_to: "{{ hostname }}"

  - name: Ansible remove files in  /var/www/html/ignition/
    file:
      path: /var/www/html/ignition/
      state: absent
    with_items: "{{ files_to_delete.files }}"
    when: clean is defined
    delegate_to: "{{ hostname }}"
    
  - name: configure web server files
    script: "configure-webserver.sh --some-argument  {{ user_home.stdout }}"
    delegate_to: "{{ hostname }}"