- hosts: "{{ hostname }}"

  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter_username }}"
    GOVC_PASSWORD: "{{ vcenter_password }}"
    GOVC_URL: "https://{{ vcenter_hostname }}"
    GOVC_INSECURE: 1

  vars:
    folder : "/{{ vmware_datacenter }}/vm/{{ config.clusterName }}"

  tasks:

  - name: Create the vCenter folder by the same name as the cluster
    command: "/usr/local/bin/govc folder.create {{ folder }}"
    when: vcenter_preqs_met is not defined
