- hosts: localhost

  vars:

    masterContent: "{{ lookup('file', '{{ playbook_dir }}/install-dir/master.64' )}}"
    workerContent: "{{ lookup('file', '{{ playbook_dir }}/install-dir/worker.64' )}}"
    appendBootstrapContent: "{{ lookup('file', '{{ playbook_dir }}/install-dir/append-bootstrap.64' )}}"
    folder : "/{{ vcenter.datacenter }}/vm/{{ config.clusterName }}"
  
  tasks:
 
  - name: "Bootstrap base64"
    debug:
      msg: "{{ appendBootstrapContent }}" 
      verbosity: 1
  - name: "Master base64"
    debug:
      msg: "{{ masterContent }}" 
      verbosity: 1
  - name: "Worker base64 "
    debug:
      msg: "{{ workerContent }}" 
      verbosity: 1

  - name: Create bootstrap VM from the template
    vmware_guest:
      hostname: "{{ vcenter.ip }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      datacenter: dc
      validate_certs: no
      folder: "{{ folder }}"
      name: bootstrap 
      state: poweredon
      template: "{{ vcenter.templateName }}"
      disk:
      - size_gb: 120 
        type: thin
        datastore: "{{ vcenter.datastore }}"
      hardware:
        memory_mb: 16384 
        num_cpus: 4
        memory_reservation_lock: True
      networks:
      - name: VM Network
        mac: "00:50:56:a8:aa:a1" 
      wait_for_ip_address: no 
      customvalues:
        - key: guestinfo.ignition.config.data
          value: "{{ appendBootstrapContent }}"

  - name: Create master VMs from ther template
    vmware_guest:
      hostname: "{{ vcenter.ip }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      datacenter: dc
      validate_certs: no
      folder: "{{ folder }}"
      name: "{{ item.name }}"
      state: poweredon
      template: "{{ vcenter.templateName }}"
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ vcenter.datastore }}" 
      hardware:
        memory_mb: 16384
        num_cpus: 4
        memory_reservation_lock: True
      networks:
      - name: VM Network
        mac: "{{ item.mac }}"
      wait_for_ip_address: no
      customvalues:
       - key: guestinfo.ignition.config.data
         value: "{{ masterContent }}"
    loop:
      - { name : "master0", mac: "00:50:56:a8:aa:a2"}
      - { name : "master1", mac: "00:50:56:a8:aa:a3"}
      - { name : "master2", mac: "00:50:56:a8:aa:a4"}

  - name: Create worker VMs from the template
    vmware_guest:
      hostname: "{{ vcenter.ip }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      datacenter: dc
      validate_certs: no
      folder: "{{ folder }}"
      name: "{{ item.name }}"
      state: poweredon
      template: "{{ vcenter.templateName }}"
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ vcenter.datastore }}"
      hardware:
        memory_mb: 16384
        num_cpus: 4
        memory_reservation_lock: True
      networks:
      - name: VM Network
        mac: "{{ item.mac }}"
      wait_for_ip_address: no
      customvalues:
       - key: guestinfo.ignition.config.data
         value: "{{ workerContent }}"
    loop:
      - { name : "worker0", mac: "00:50:56:a8:aa:a5"}
      - { name : "worker1", mac: "00:50:56:a8:aa:a6"}
      - { name : "worker2", mac: "00:50:56:a8:aa:a7"}
