---
- hosts: "{{ hostname }}"
  tasks:
  - name: Waiting for bootstrap Complete
    shell: |
      #/bin/bash
      openshift-install --dir=/root/install-dir wait-for bootstrap-complete --log-level debug | tee /tmp/bootstrap-complete.log
    changed_when: false
  - name: Wait for bootstrap complete to be found in file
    wait_for:
      path: "/tmp/bootstrap-complete.log"
      search_regex: "Bootstrap status: complete"
      delay: 30
      timeout: 60
      msg: "DEBUG Bootstrap status: complete "
  - name: Remove /tmp/bootstrap-complete.log
    file:
      path: /tmp/bootstrap-complete.log
      state: absent
