- hosts: "{{ hostname }}"

  environment: 
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter_username }}"
    GOVC_PASSWORD: "{{ vcenter_password }}"
    GOVC_URL: "https://{{ vcenter_hostname }}"
    GOVC_INSECURE: 1

  vars:
    folder : "/{{ vmware_datacenter }}/vm/{{ config.clusterName }}"    

  tasks:
  - name: get user home directory
    shell: >
            getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: Download the ova file 
    get_url:
      url: "{{ download.ova }}"
      dest: "{{ user_home.stdout }}/downloads/{{templateName}}.ova"
      validate_certs: no
    when: vcenter_preqs_met is not defined
  
  - name: "Get  {{ download.ova }} sha information"
    stat:
      path: "{{ user_home.stdout }}/downloads/{{templateName}}.ova"
      checksum_algorithm: sha256
    register: ova_name_sha
   
  - name: 
    debug: 
      var: ova_name_sha
    failed_when: ova_sha != ova_name_sha.stat.checksum

  - name: Import the OVA file into the folder in vCenter 
    command: "/usr/local/bin/govc import.ova -options={{ user_home.stdout }}/vra.json -folder={{ folder }} -name={{ templateName }} {{ user_home.stdout }}/downloads/{{templateName}}.ova"
    when: vcenter_preqs_met is not defined

  - name: Remove the Network Adapter  
    command: "/usr/local/bin/govc device.remove -vm {{ folder }}/{{ templateName }} ethernet-0"
    when: vcenter_preqs_met is not defined

  - name: Update VM options on the template
    command: "/usr/local/bin/govc vm.change -vm {{ folder }}/{{ templateName }} -latency high -e=disk.EnableUUID=TRUE -e=guestinfo.ignition.config.data.encoding=base64 -e=guestinfo.ignition.config.data=blah"
    when: vcenter_preqs_met is not defined      