---
- hosts: "{{ hostname }}"
  tasks:
    - name: get user home directory
      shell: >
              getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home

    - name: Setting facts 
      set_fact:
        templateName : "{{ templateName }}"
        folder : "/{{ vmware_datacenter }}/vm/{{ config.clusterName }}"
        datastore: "{{ vmware_datastore }}"

    - name: get append-bootstrap.64 dhcp ignition file
      shell: >
          cat  {{ user_home.stdout }}/install-dir/append-bootstrap.64
      changed_when: false
      register: bootstrap64
      when: configure_static_ips == False

    - name: get append-bootstrap.64 static ignition file
      shell: >
          cat   {{ user_home.stdout }}/ocp4-utils/configFiles/bootstrap.{{ config.clusterName }}.{{ config.baseDomain }}.64
      changed_when: false
      register: bootstrap64
      when: 
        - configure_static_ips == True
        -  bootstrap64.stdout != ""

    - name: "Bootstrap base64"
      debug:
        msg: "{{ bootstrap64.stdout }}"

    - name: Create bootstrap VM from the template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vmware_datacenter }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: bootstrap
        state: poweredoff
        template: "{{ templateName }}"
        disk:
        - size_gb: 120
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: 16384
          num_cpus: 4
          memory_reservation_lock: True
        networks:
        - name: "{{ vmware_network }}"
          mac: "{{ macaddr }}"
        wait_for_ip_address: no
        customvalues:
          - key: guestinfo.ignition.config.data
            value: "{{ bootstrap64.stdout }}"