---
- hosts: "{{ hostname }}"
  tasks:
  - name: get user home directory
    shell: >
            getent passwd {{ ansible_user_id }}  | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home
  
  #- pip:
  #    requirements: requirements.txt

  - name: Setting facts 
    set_fact:
      templateName : "{{ templateName }}"
      folder : "/{{ vmware_datacenter }}/vm/{{ config.clusterName }}"
      datastore: "{{ vmware_datastore }}"

  - name: Deploy Bootstrap Node
    include: setup-vcenter-vms-bootstrap-loop.yml

  - name: Deploy Master Nodes
    include: setup-vcenter-vms-master-loop.yml
    loop: "{{ masters }}"

  - name: Deploy Worker Nodes
    include: setup-vcenter-vms-worker-loop.yml
    loop: "{{ workers }}"