kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-pvc
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ""{{ nfs_size }}""
  storageClassName: nfs-storage-provisioner
  volumeMode: Filesystem
